from unittest import TestCase

from src.days.day08.part_1 import run as part_1_run
from src.days.day08.part_2 import run as part_2_run

test_data = '''
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
'''


class Test(TestCase):

    def test_part_1(self):
        self.assertEqual(14, part_1_run(test_data.strip().splitlines()))

    def test_part_2(self):
        self.assertEqual(34, part_2_run(test_data.strip().splitlines()))
